### ISSUE TITLE
If habit is added with no start or end, app will crash when trying to edit that habit

### ISSUE THREAD

**Issue by jboileau99** [CMPUT301F21T31/Habit#50]
- Try adding habit but pick no start or end, then click that habit from list to edit it, will crash
- We could either enforce that you pick a start or end (don't leave the add activity if not selected), or set them to default values

![image](https://user-images.githubusercontent.com/45305362/140277026-5a178855-0946-4715-9145-ae8b42b6ddd2.png)

**Comment by lewisning** [comment]
bug fixed
